services:
  web:
    image: ghcr.io/hwalker928/secretsanta:latest
    environment:
      ADMIN_USER: Harry
      VALID_NAMES: alice,ben,charlie,david
      BUDGET: 10

      REROLL_ENABLED: true

      MYSQL_DATABASE: secretsanta
      MYSQL_USER: santa
      MYSQL_PASSWORD: SantasLittleHelper2024
      MYSQL_HOST: db
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: SantasLittleHelper2024
      MYSQL_DATABASE: secretsanta
      MYSQL_USER: santa
      MYSQL_PASSWORD: SantasLittleHelper2024
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
